/**
*The Cat class represents a cat with specific attributes such as name, species,
* claws, tail, whiskers, and collar. It provides methods to access and modify these attributes.
*Initnal code generated by Copilot expect the whiskers and sharpteeth instance varibles and its methods.
*/
public class Cat {
    // Instance variables
    private String name;
    private String species;
    private boolean claws;
    private boolean tail;
    private boolean whiskers;
    private boolean sharpTeeth;
    private Collar collar;

    /**
     * Constructs a Cat object with the specified attributes.
     *
     * @param name       the name of the cat
     * @param species    the species of the cat
     * @param claws      whether the cat has claws
     * @param tail       whether the cat has a tail
     * @param whiskers   whether the cat has whiskers
     * @param sharpTeeth whether the cat has sharp teeth
     * @param collar     the collar object associated with the cat
     */
    public Cat(String name, String species, boolean claws, boolean tail, boolean whiskers, boolean sharpTeeth, Collar collar) {
        this.name = name;
        this.species = species;
        this.claws = claws;
        this.tail = tail;
        this.whiskers = whiskers;
        this.sharpTeeth = sharpTeeth;
        this.collar = collar;
    }

    /**
     * Gets the name of the cat.
     *
     * @return the name of the cat
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the cat.
     *
     * @param name the new name of the cat
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the species of the cat.
     *
     * @return the species of the cat
     */
    public String getSpecies() {
        return species;
    }

    /**
     * Sets the species of the cat.
     *
     * @param species the new species of the cat
     */
    public void setSpecies(String species) {
        this.species = species;
    }

    /**
     * Checks if the cat has claws.
     *
     * @return true if the cat has claws, false otherwise
     */
    public boolean hasClaws() {
        return claws;
    }

    /**
     * Sets whether the cat has claws.
     *
     * @param claws true if the cat has claws, false otherwise
     */
    public void setClaws(boolean claws) {
        this.claws = claws;
    }

    /**
     * Checks if the cat has a tail.
     *
     * @return true if the cat has a tail, false otherwise
     */
    public boolean hasTail() {
        return tail;
    }

    /**
     * Sets whether the cat has a tail.
     *
     * @param tail true if the cat has a tail, false otherwise
     */
    public void setTail(boolean tail) {
        this.tail = tail;
    }

    /**
     * Checks if the cat has whiskers.
     *
     * @return true if the cat has whiskers, false otherwise
     */
    public boolean hasWhiskers() {
        return whiskers;
    }

    /**
     * Sets whether the cat has whiskers.
     *
     * @param whiskers true if the cat has whiskers, false otherwise
     */
    public void setWhiskers(boolean whiskers) {
        this.whiskers = whiskers;
    }

    /**
     * Checks if the cat has sharp teeth.
     *
     * @return true if the cat has sharp teeth, false otherwise
     */
    public boolean hasSharpTeeth() {
        return sharpTeeth;
    }

    /**
     * Sets whether the cat has sharp teeth.
     *
     * @param sharpTeeth true if the cat has sharp teeth, false otherwise
     */
    public void setSharpTeeth(boolean sharpTeeth) {
        this.sharpTeeth = sharpTeeth;
    }

    /**
     * Gets the collar of the cat.
     *
     * @return the collar object
     */
    public Collar getCollar() {
        return collar;
    }

    /**
     * Sets the collar of the cat.
     *
     * @param collar the new collar object
     */
    public void setCollar(Collar collar) {
        this.collar = collar;
    }

    /**
     * Makes the cat produce a sound.
     */
    public void sound() {
        System.out.println("Meow!");
    }

    /**
     * Makes the cat move its tail if it has one.
     */
    public void tailMove() {
        if (tail) {
            System.out.println("The cat's tail is moving.");
        } else {
            System.out.println("This cat has no tail to move.");
        }
    }

    /**
     * Makes the cat scratch if it has claws.
     */
    public void scratch() {
        if (claws) {
            System.out.println("The cat is scratching.");
        } else {
            System.out.println("This cat has no claws to scratch.");
        }
    }

    /**
     * Returns a string representation of the Cat object.
     *
     * @return a string representation of the Cat object
     */
    @Override
    public String toString() {
        return "Cat{name='" + name + "', species='" + species + "', claws=" + claws +
               ", tail=" + tail + ", whiskers=" + whiskers + ", sharpTeeth=" + sharpTeeth +
               ", collar=" + (collar != null ? collar.getColor() + " " + collar.getSize() : "none") + "}";
    }
}