/**
 * The Collar class represents a collar that a cat can wear. It includes attributes
 * such as color and size. Java Doc comments were generated by AI but not the code itself.
 */
public class Collar {

    // Instance variables
    private String color;
    private String size;

    /**
     * Constructs a Collar object with the specified attributes.
     *
     * @param color the color of the collar
     * @param size  the size of the collar
     */
    public Collar(String color, String size) {
        this.color = color;
        this.size = size;
    }

    /**
     * Gets the color of the collar.
     *
     * @return the color of the collar
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the color of the collar.
     *
     * @param color the new color of the collar
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * Gets the size of the collar.
     *
     * @return the size of the collar
     */
    public String getSize() {
        return size;
    }

    /**
     * Sets the size of the collar.
     *
     * @param size the new size of the collar
     */
    public void setSize(String size) {
        this.size = size;
    }
}
