/**
 * The MethodTester class is used to test the functionality of the Cat and Collar classes.
 * It demonstrates creating instances of these classes, updating their attributes, and
 * displaying their values. 
 * Java doc comments were generated by AI but not the code itself other than debugging.
 */
public class MethodTester {
    /**
     * The main method is the entry point of the program. It creates instances of the
     * Collar and Cat classes, updates their attributes, and displays the results.
     *
     * @param args command-line arguments (not used in this program)
     */
    public static void main(String[] args) {
        // Create a Collar instance with a color
        Collar blueCollar = new Collar("Blue", "Medium");

        // Create a Cat instance with initial attributes
        Cat cat1 = new Cat("Whiskers", "Siamese", true, true, true, true, blueCollar);

        // Display initial cat name
        System.out.println("Initial Cat Name: " + cat1.getName());

        // Update the cat's name
        cat1.setName("Garfield");
        System.out.println("Updated Cat Name: " + cat1.getName());

        // Display initial collar color
        System.out.println("Initial Collar Color: " + cat1.getCollar().getColor());

        // Update the cat's collar
        Collar redCollar = new Collar("Red", "Small");
        cat1.setCollar(redCollar);
        System.out.println("Updated Collar Color: " + cat1.getCollar().getColor());
    }
}